Add VPC and scripts for Terraform workspaces and plans

diff --git a/scripts/terraform-init b/scripts/terraform-init
--- a/scripts/terraform-init
+++ b/scripts/terraform-init
@@ -4,5 +4,19 @@ set -e
 
 cd "$(dirname "$0")/.."
 
+environment="$1"
+
+if [[ -z "${environment}" ]]; then
+  echo "ERROR: no value for arg 1: environment"
+  exit 1
+fi
+
 echo "+++ Initializing Terraform"
 ./scripts/terraform init
+
+if ! ./scripts/terraform workspace select "${environment}"; then
+  echo "+++ Creating Terraform workspace for environment: ${environment}"
+  ./scripts/terraform workspace new "${environment}"
+else
+  echo "--- Switched Terraform workspace to: ${environment}"
+fi
diff --git a/scripts/terraform-plan b/scripts/terraform-plan
--- a/scripts/terraform-plan
+++ b/scripts/terraform-plan
@@ -4,7 +4,16 @@ set -e
 
 cd "$(dirname "$0")/.."
 
-./scripts/terraform-init
+environment="$1"
 
-echo "+++ Running Terraform plan"
-./scripts/terraform plan
+if [[ -z "${environment}" ]]; then
+  echo "ERROR: no value for arg 1: environment"
+  exit 1
+fi
+
+./scripts/terraform-init "${environment}"
+
+echo "+++ Running Terraform plan for environment: ${environment}"
+./scripts/terraform plan \
+  --var-file "${environment}.tfvars" \
+  --out "plans/${environment}"
